import csv
import json
import contextlib
import io
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from evidence_office.cli import main


class CliBehaviourTests(unittest.TestCase):
    def test_version_flag_is_available(self) -> None:
        stdout = io.StringIO()
        with contextlib.redirect_stdout(stdout):
            with self.assertRaises(SystemExit) as raised:
                main(["--version"])

        self.assertEqual(raised.exception.code, 0)
        self.assertIn("evidence-office 0.6.0", stdout.getvalue())

    def test_build_writes_machine_and_human_reports(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            with (root / "results.csv").open("w", encoding="utf-8", newline="") as handle:
                writer = csv.DictWriter(handle, fieldnames=["metric", "value"])
                writer.writeheader()
                writer.writerow({"metric": "efficiency", "value": "0.91"})
            (root / "manifest.json").write_text(json.dumps({
                "project": "Build demo",
                "sources": [{"path": "results.csv"}],
                "claims": [{
                    "id": "C-001",
                    "statement": "Efficiency is 0.91.",
                    "status": "verified",
                    "sources": [{"path": "results.csv", "anchor": "row:1/field:value"}],
                }],
            }), encoding="utf-8")
            out_dir = root / "dist"

            exit_code = main(["build", str(root / "manifest.json"), "--out", str(out_dir)])

            self.assertEqual(exit_code, 0)
            self.assertTrue((out_dir / "evidence-report.json").is_file())
            self.assertTrue((out_dir / "evidence-report.html").is_file())
            report = json.loads((out_dir / "evidence-report.json").read_text(encoding="utf-8"))
            self.assertEqual(report["status"], "passed")
            self.assertIn("Generated by evidence-office", (out_dir / "evidence-report.html").read_text(encoding="utf-8"))

    def test_cli_runs_init_intake_and_build_as_one_real_workflow(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            workspace = Path(directory) / "package"
            self.assertEqual(main(["init", "--out", str(workspace), "--project", "CLI workflow"]), 0)
            source = workspace / "sources" / "results.csv"
            source.write_text("metric,value\nefficiency,0.91\n", encoding="utf-8")
            manifest_path = workspace / "manifest.json"
            self.assertEqual(main(["intake", str(manifest_path), "--root", str(workspace), "sources/results.csv"]), 0)
            self.assertEqual(main([
                "claim", "add", str(manifest_path),
                "--id", "C-001",
                "--statement", "Efficiency is 0.91.",
                "--status", "verified",
                "--source", "sources/results.csv",
                "--anchor", "row:1/field:value",
                "--root", str(workspace),
            ]), 0)

            out_dir = workspace / "dist"
            self.assertEqual(main(["build", str(manifest_path), "--out", str(out_dir)]), 0)
            self.assertIn("C-001", (out_dir / "evidence-map.md").read_text(encoding="utf-8"))
            self.assertTrue((out_dir / "source-index.json").is_file())

    def test_demo_is_explicitly_synthetic_and_validates(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            out_dir = Path(directory) / "demo"
            self.assertEqual(main(["demo", "--out", str(out_dir)]), 0)
            manifest = out_dir / "manifest.json"
            self.assertTrue(manifest.is_file())
            dist_dir = out_dir / "dist"
            self.assertEqual(main(["build", str(manifest), "--out", str(dist_dir)]), 0)
            self.assertIn("synthetic", manifest.read_text(encoding="utf-8").lower())
            report = json.loads((dist_dir / "evidence-report.json").read_text(encoding="utf-8"))
            self.assertEqual(report["status"], "passed_with_warnings")
            self.assertGreaterEqual(report["summary"]["warnings"], 1)

    def test_demo_refuses_to_overwrite_a_nonempty_directory(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            out_dir = Path(directory) / "existing"
            out_dir.mkdir()
            marker = out_dir / "keep.txt"
            marker.write_text("user data", encoding="utf-8")
            stderr = io.StringIO()

            with contextlib.redirect_stderr(stderr):
                exit_code = main(["demo", "--out", str(out_dir)])

            self.assertEqual(exit_code, 2)
            self.assertEqual(marker.read_text(encoding="utf-8"), "user data")
            self.assertFalse((out_dir / "manifest.json").exists())

    def test_malformed_manifest_returns_a_concise_cli_error(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            manifest = Path(directory) / "broken.json"
            manifest.write_text("{not-json", encoding="utf-8")
            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                exit_code = main(["validate", str(manifest)])

            self.assertEqual(exit_code, 2)
            self.assertIn("error:", stderr.getvalue())
            self.assertNotIn("Traceback", stderr.getvalue())

    def test_malformed_manifest_entries_are_not_silently_discarded(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "source.txt").write_text("evidence\n", encoding="utf-8")
            manifest = root / "manifest.json"
            manifest.write_text(json.dumps({
                "project": "Malformed entries",
                "sources": [{"path": "source.txt"}, 42],
                "claims": [],
            }), encoding="utf-8")
            stderr = io.StringIO()

            with contextlib.redirect_stderr(stderr):
                exit_code = main(["validate", str(manifest)])

            self.assertEqual(exit_code, 2)
            self.assertIn("sources", stderr.getvalue())
            self.assertNotIn("Traceback", stderr.getvalue())

    def test_unknown_manifest_fields_are_not_silently_discarded(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "source.txt").write_text("evidence\n", encoding="utf-8")
            manifest = root / "manifest.json"
            manifest.write_text(json.dumps({
                "project": "Unknown field",
                "project_meta": {"owner": "reviewer"},
                "sources": [{"path": "source.txt"}],
                "claims": [],
            }), encoding="utf-8")
            stderr = io.StringIO()

            with contextlib.redirect_stderr(stderr):
                exit_code = main(["validate", str(manifest)])

            self.assertEqual(exit_code, 2)
            self.assertIn("Unknown manifest field", stderr.getvalue())
            self.assertIn("project_meta", stderr.getvalue())

    def test_deeply_nested_manifest_returns_a_concise_cli_error(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            manifest = Path(directory) / "deep.json"
            manifest.write_text("{}", encoding="utf-8")
            stderr = io.StringIO()
            with mock.patch("evidence_office.validator.json.load", side_effect=RecursionError("too deep")):
                with contextlib.redirect_stderr(stderr):
                    exit_code = main(["validate", str(manifest)])

            self.assertEqual(exit_code, 2)
            self.assertIn("too deeply nested", stderr.getvalue())
            self.assertNotIn("Traceback", stderr.getvalue())

    def test_invalid_unicode_manifest_text_is_rejected_before_rendering(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "source.txt").write_text("evidence\n", encoding="utf-8")
            manifest = root / "manifest.json"
            manifest.write_text(json.dumps({
                "project": "Unicode",
                "sources": [{"path": "source.txt"}],
                "claims": [{
                    "id": "C-001",
                    "statement": "bad \ud800 text",
                    "status": "verified",
                    "sources": [{"path": "source.txt", "anchor": "line:1"}],
                }],
            }), encoding="utf-8")
            stderr = io.StringIO()

            with contextlib.redirect_stderr(stderr):
                exit_code = main(["validate", str(manifest)])

            self.assertEqual(exit_code, 2)
            self.assertIn("valid Unicode", stderr.getvalue())

    def test_generic_output_io_error_is_reported_without_a_traceback(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "source.txt").write_text("evidence\n", encoding="utf-8")
            manifest = root / "manifest.json"
            manifest.write_text(json.dumps({
                "project": "I/O failure",
                "sources": [{"path": "source.txt"}],
                "claims": [],
            }), encoding="utf-8")
            stderr = io.StringIO()

            with mock.patch("pathlib.Path.write_text", side_effect=OSError("disk unavailable")):
                with contextlib.redirect_stderr(stderr):
                    exit_code = main([
                        "validate", str(manifest), "--format", "json", "--out", str(root / "report.json"),
                    ])

            self.assertEqual(exit_code, 2)
            self.assertIn("disk unavailable", stderr.getvalue())
            self.assertNotIn("Traceback", stderr.getvalue())

    def test_existing_file_output_path_returns_a_concise_cli_error(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            output_path = Path(directory) / "already-a-file"
            output_path.write_text("do not overwrite", encoding="utf-8")
            stderr = io.StringIO()

            with contextlib.redirect_stderr(stderr):
                exit_code = main(["init", "--out", str(output_path), "--project", "Demo"])

            self.assertEqual(exit_code, 2)
            self.assertIn("error:", stderr.getvalue())
            self.assertNotIn("Traceback", stderr.getvalue())

    def test_init_rejects_a_blank_project_before_creating_files(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            workspace = Path(directory) / "blank"
            stderr = io.StringIO()

            with contextlib.redirect_stderr(stderr):
                exit_code = main(["init", "--out", str(workspace), "--project", "   "])

            self.assertEqual(exit_code, 2)
            self.assertFalse(workspace.exists())
            self.assertIn("must not be empty", stderr.getvalue())

    def test_init_rejects_invalid_unicode_before_creating_files(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            workspace = Path(directory) / "invalid-unicode"
            stderr = io.StringIO()

            with contextlib.redirect_stderr(stderr):
                exit_code = main([
                    "init", "--out", str(workspace), "--project", "bad\ud800project",
                ])

            self.assertEqual(exit_code, 2)
            self.assertFalse(workspace.exists())
            self.assertIn("valid Unicode", stderr.getvalue())

    def test_strict_build_treats_review_warnings_as_blocking(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            out_dir = Path(directory) / "demo"
            self.assertEqual(main(["demo", "--out", str(out_dir)]), 0)

            exit_code = main([
                "build", str(out_dir / "manifest.json"),
                "--out", str(out_dir / "dist"),
                "--strict",
            ])

            self.assertEqual(exit_code, 1)

    def test_audit_command_detects_source_drift(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            workspace = Path(directory) / "demo"
            self.assertEqual(main(["demo", "--out", str(workspace)]), 0)
            manifest = workspace / "manifest.json"
            dist = workspace / "dist"
            self.assertEqual(main(["build", str(manifest), "--out", str(dist)]), 0)
            (workspace / "sources" / "simulation_results.csv").write_text(
                "run,tracking_error_m,energy_kwh\nsynthetic-01,0.18,2.41\nsynthetic-02,0.99,2.37\n",
                encoding="utf-8",
            )
            audit_out = workspace / "audit.json"

            exit_code = main([
                "audit", str(manifest), "--package", str(dist),
                "--format", "json", "--out", str(audit_out),
            ])

            self.assertEqual(exit_code, 1)
            payload = json.loads(audit_out.read_text(encoding="utf-8"))
            self.assertEqual(payload["report_type"], "drift_audit")
            self.assertIn("SOURCE_DRIFTED", {issue["code"] for issue in payload["issues"]})


if __name__ == "__main__":
    unittest.main()
